### ISSUE TITLE
pv mode 1 and 2 switched?

### ISSUE THREAD

**Issue by nickelbert** [marcelblijleven/goodwe#10]
PV1 has 0W and PV2 has 17W but pv mode shows PV1 producing power and PV2 not connected

Model: Goodwe GW8K-ET

![Screenshot 2022-03-05 232256](https://user-images.githubusercontent.com/11795209/156901705-94517e7e-c5ba-465a-b25e-c37747db071d.png)

**Comment by lyricnz** [comment]
Which model inverter?  Can you provide the debug output?  logging.basicConfig(level=logging.DEBUG)

**Comment by gowima** [comment]
Same for me forGW29K9-ET inverter with current (2024-01-14) version of goodwe module. Pypi module 0.2.33 with byte address mode was ok for me.

The GW29K9-ET inverter has 3 MPPT. I could watch the above decribed behavior for PV3 and PV4. 

This seems to a problem with byte order (big endian vs little endian) in the current implementation using register address mode. Have a look at my fork of goodwe at gowima/goodwe (be aware this is still work in progress).

**Comment by mletenay** [comment]
Fixed in 88a1ff7e4560f4034528304a744dfe3fdc7d51da
Thanks @gowima
