### ISSUE TITLE
Confused about power readings

### ISSUE THREAD

**Issue by jacereda** [marcelblijleven/goodwe#32]
I'm confused about the following code:

https://github.com/marcelblijleven/goodwe/blob/ce6be71a336a2283acd56b04a15f490519ee4d31/goodwe/sensor.py#L397

Why should a 4 bytes value reading need such transformation?

**Comment by mletenay** [comment]
Since it is now being parsed as signed int, it is probably not necessary anymore, it seems to be remnant of very old code, but I have to verify it.

**Comment by mletenay** [comment]
I have reimplemented power sensors and that code is no longer there. Thanks for pointing out.
