### ISSUE TITLE
e_day_imp without value

### ISSUE THREAD

**Issue by AdriVillaB** [marcelblijleven/goodwe#39]
Hi, 

I have a GW3600-EH inverter and all the entities are properly popullated, but the e_day_imp does not. I mainly use the library directly on HomeAssistant, but I also tried it as standalone.

Is there any way to find why this happens? How can I share with you more data to debug this?

Thanks!

**Comment by mletenay** [comment]
There's nothing to fix, values are just taken from inverter registers.
However the e_day_imp is most likely not the value you think it is.
AFAIK, it does not represent daily import from grid (measured by meter), but daily import of inverter to its system, i.e. amount of imported grid energy stored into battery.
Fro the real grid import, there is no daily sensor, only the meter_e_total_imp
