### ISSUE TITLE
e_day_imp returns no data

### ISSUE THREAD

**Issue by gustonator** [marcelblijleven/goodwe#40]
Hi,
I'm using the module in my custom made prometheus exporter, and it's great!
However, I found out, that the metric "e_day_imp" returns no data.

e_total:                  Total PV Generation = 1183.2 kWh
e_day:                    Today's PV Generation = 19.0 kWh
e_total_exp:             Total Energy (export) = 1145.3 kWh
h_total:                   Hours Total = 3839 h
e_day_exp:               Today Energy (export) = 8.1 kWh
e_total_imp:             Total Energy (import) = 16.9 kWh
e_day_imp:               Today Energy (import) = 0.0 kWh
e_load_total:            Total Load = 3849.6 kWh
e_load_day:              Today Load = 12.7 kWh

Is the code for this metric correct? 

Also, the values somehow don't correspond to SemsPortal.
And it looks like the e_total_exp is switched with e_total_imp, because I have imported more power FROM grid, than sent into grid.

I'm using  the GW10K-ET Inverter.

**Comment by mletenay** [comment]
The values are taken directly from inverter and yes they are correct.
AFAIK e_day_imp represents daily energy inverter imported from grid into its usage/battery, i.e. unless you charge battery in eco mode from grid, it is most of the time 0.
The total values are again import/export at inverter, not at the grid meter so they are ok.
