### ISSUE TITLE
Standby mode?

### ISSUE THREAD

**Issue by liebefuroscar** [marcelblijleven/goodwe#42]
I´m using my Goodwe EM5048 with DIY battery. 
I have an electricity tariff with cheap hours and expensive hours, in the VERY cheap ones I am interested in charging the battery and in the VERY expensive ones I am interested in discharging the battery. But there are some hours that are not cheap enough to upload and not expensive enough to download. I have tried setting ECO CHARGE/DISCHARGE to 0% but it charges/discharges uncontrollably. The closest thing to what I need is to put ecomode at 1% and it only draws 1A. but is there the possibility of a "standby mode" that the battery current stays at 0A?

**Comment by mletenay** [comment]
AFAIK, the "backup mode" is exactly for that, it functions like big UPS then. 
As long as there is grid power, the battery is just being charged or standby.
It discharges only when grid fails.

**Comment by liebefuroscar** [comment]
![image](https://user-images.githubusercontent.com/25435711/221366679-400401df-fbf4-4a55-9944-e5f4d9233abf.png)
![image](https://user-images.githubusercontent.com/25435711/221366687-5fec2db2-6876-446a-ad2f-f3a3cfbc7a0b.png)
When I put backup mode download the battery towards the consumption of my house

**Comment by mletenay** [comment]
Try to change the mode from PvMaster or SolarGo.
Maybe the problem from #164 is affecting you.
