### ISSUE TITLE
Meter Total Energy import and export swapped

### ISSUE THREAD

**Issue by cjgarciao** [marcelblijleven/goodwe#47]
Hello,
I have a GW6000-EH inverter, which I monitor with Home Assistant.  I have switched it off and when I switched it on 'Meter Total Energy (import)' and 'Meter Total Energy (export)' have been swapped. I restarted it again and one piece of data was recorded correctly, but then it continued to swap.
Thanks,
Carlos.

![image](https://user-images.githubusercontent.com/13287860/233281815-e61f855d-86b4-4240-9498-ee72b0c07b60.png)

**Comment by mletenay** [comment]
Sorry, no clue how this can happen.
