### ISSUE TITLE
GW20K-ET Some values are always 0

### ISSUE THREAD

**Issue by t4e-dev** [marcelblijleven/goodwe#58]
Hi,

thanks for your hard work!
I have an inverter  GW20K-ET

```
meter_e_total_exp:               Meter Total Energy (export) = 0.0 kWh
meter_e_total_imp:               Meter Total Energy (import) = 0.0 kWh
```
The values, that are needed for Homeassistant Energy Dashboard are always 0 in the requests.
Sadly I do not really know how to analyse the datagram.
Solar-Go seems to successfully decode these values. So in theory, they are there .-)

I also have the issue that Semsportal is no longer available once HomeAssistant starts polling the inverter.
If there is a solution for that I would be thankful as well. 

Thanks for your help...

**Comment by Jan-Antos** [comment]
I have GW15K-ET. Same problem. Meter Total Energy reads always 0. 
Also PV2 panels status is wrong (always reads "not connected"), PV1 string power is equal to PV power (but I have two strings), PV2 power always reads 0, but PV2 current and PV2 voltage reads ok. 
If you set polling interval for 180sec or above, SEMS communication is restored

**Comment by t4e-dev** [comment]
Is there anything I can help to include these devices ?
Provide datagrams, or something like this ?

**Comment by DerBauch78** [comment]
GW15K-ET in my home and same for me here too.
The entity „Total energy export/import“ is working,  but it seems that this is the oberall energy coming from the inverter. Could there be a way to calculate the meter total energy from theese values?
![Uploading IMG_0359.jpeg…]()

**Comment by mletenay** [comment]
It seems the ETT inverters use different modbus registers than ETU.
I can try to reverse engineer some data from mobile app again, but can't promise when or if possible at all ...

**Comment by mletenay** [comment]
We now have the manufacturer's description of modbus registers of ETT inverters and there are no relevant differences to ETU inverters. So the "meter" values should be read and decoded properly.
Couldn't it be something is wrong with your meter installation ?

**Comment by t4e-dev** [comment]
Sounds great!! Thanks a lot. Wish I could help :-)

**Comment by mletenay** [comment]
Library with the "CT2" was released and HACS integration was released as weel, hope it helps.
