### ISSUE TITLE
Eco Mode + Discharge Battery

### ISSUE THREAD

**Issue by okanano** [marcelblijleven/goodwe#65]
Hi guys, I have a GW5048D-ES inverter and a few questions about it:

1. How can I enable the Eco Mode (Charge / Discharge) at specific times using this library?
2. Imagine this scenario: It is a cloudy day which means not much PV, in that case, I want to discharge the battery into the grid, is that possible?

**Comment by mletenay** [comment]
Use [Home Assistant](https://www.home-assistant.io/).
