### ISSUE TITLE
Support for MS G3 inverter

### ISSUE THREAD

**Issue by yldog9** [marcelblijleven/goodwe#66]
Hi, Support for MS G3 inverter would be great, have attached the protocol doc provided by goodwe
Currently DT setting picks up most info however doesn't provide PV3 data and contents of register identifying why the system is power limiting would also be useful

[GoodWe grid-tied DNSG3 MSG3 XSG3 SDTG3 series Modbus protocal-customer version.pdf](https://github.com/marcelblijleven/goodwe/files/13872838/GoodWe.grid-tied.DNSG3.MSG3.XSG3.SDTG3.series.Modbus.protocal-customer.version.pdf)

debug log also attached
[home-assistant_goodwe_2024-01-09T11-08-51.717Z.log](https://github.com/marcelblijleven/goodwe/files/13872941/home-assistant_goodwe_2024-01-09T11-08-51.717Z.log)

**Comment by mletenay** [comment]
Done in v0.3.0
