### ISSUE TITLE
Sell / Sold per day

### ISSUE THREAD

**Issue by oubrecht-com** [marcelblijleven/goodwe#70]
Hi,
I would like to ask you, how can I get "sell" or "sold" value for actual day? It is value in kWh what I sell to distribution network. SEMS portal has this value.
Value e_day_exp is not good for it.

**Comment by mletenay** [comment]
There is no such "daily" register for grid boundary (meter) measurements.
There is only 'meter_e_total_exp' - you need to calculate daily difference manually.
