### ISSUE TITLE
How to disable battery charging?

### ISSUE THREAD

**Issue by lubond32** [marcelblijleven/goodwe#79]
Great work guys!
I have GW10KN-ET + Pylontech Force H2 battery pack.  Library is extremely useful for me, thank you very much!

Let me a question:
Is it possible to temporarily limit or completely disable battery charging from PV panels?

I am following spot prices and my idea is:
1. To prioritize supply to the network before recharging the battery (especially in the morning) if a sunny day is expected and wholesale prices will decrease during the day.
2. To re-enable battery charging when spot prices fall below an acceptable value or if battery capacity is critical.

Does the library support any way to achieve this?

**Comment by mletenay** [comment]
You should be able to achieve that by limiting 'battery_charge_current'
