### ISSUE TITLE
Can't connect without package

### ISSUE THREAD

**Issue by Eniris-Siebe** [marcelblijleven/goodwe#80]
Hi,

This isn't really an issue with the package but I have a question/issue.

I am trying to connect to my goodwe inverter over modbus tcp but I can't seem to connect to either port 502 or 8899, however when using the python package I am able to connect and read out data. Is this a known problem?

**Comment by mletenay** [comment]
I am not really sure I understand the question/problem.

**Comment by Eniris-Siebe** [comment]
Hi I figured it out, I was trying to connect over TCP instead of UDP
