### ISSUE TITLE
Question: how it intepret constants like `30103` in the code base?

### ISSUE THREAD

**Issue by haarts** [marcelblijleven/goodwe#84]
Hi all,

I'm reading  the code and I'm trying to map the constants I'm seeing there to the Modbus documentation I [found](https://downloads.vodnici.net/uploads/wpforo/attachments/483/4349-1GoodweModbusPROTOCOLHybrid-ENV1-3EMseries.pdf).

The code defines stuff like this: [`Voltage("vpv1", 30103, "PV1 Voltage", Kind.PV)`](https://github.com/marcelblijleven/goodwe/blob/master/goodwe/dt.py#L22). I can't correlate the `30103` with what I read in the Modbus documentation. The `3` must be the command. But the remainder isn't clear. From the docs I figured `0500` is the address of the `vpv1` value.  How does one relate to the other?

**Comment by xhyrom** [comment]
You have old documentation. I'm not sure if [this](https://forum.iobroker.net/assets/uploads/files/1703579717824-arm.745.esg2.et30.modbus.protocol.map.20221231..v1.pdf) is the most up to date documentation but it contains the constants.
